#!/usr/env bash
readonly DIR=$1

Start="$PROJECT_HOME/$DIR"

while [ ! -f "${Start}/bnd.bnd" ]
do
  if [ "$Start" = "$PROJECT_HOME" ]
  then
    (>&2 echo 'No module here')
    exit 1
  fi
  Start=$( dirname "$Start" )
done

echo $Start

